---
 - name: "install wordpress" 
   hosts: remote_servers
   become: yes
   vars_files:
           -  vars.txt
    
   tasks:
   - name: apt update and install apache2
     apt:
             update_cache: yes
             name: apache2
             state: present
   - name: install mysql server
     apt:
             name: mysql-server
             state: present

   - name: Install php modules
     apt:
             name:
                     - php-curl
                     - php-gd 
                     - php-mbstring
                     - php-xml 
                     - php-xmlrpc
                     - php-soap
                     - php-intl 
                     - php-zip
                     - python3-pymysql
                     - php
                     - php-mysql
                     - libapache2-mod-php
             state: present

   - name: check wordpress folder existing
     stat: path=/var/www/html/wordpress
     register: check_path

   - name: download and unarchive wordpress
     unarchive:
             src: http://wordpress.org/latest.tar.gz
             dest: /var/www/html/
             remote_src: yes
     when: not check_path.stat.exists

   - name: CHOWN wordpress folder
     file:
             path: /var/www/html/wordpress
             owner: www-data
             group: www-data
     become: yes

   - name: set root mysql password
     become: yes
     mysql_user: 
            name: root 
            password: "{{ mysql_root_pass }}"
            login_user: root
            login_password: "{{ mysql_root_pass }}"
            check_implicit_admin: yes
            priv: "*.*:ALL,GRANT"
            login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Create WP mysql user
     community.mysql.mysql_user:
             name: '{{ wp_mysql_user }}'
             password: '{{ wp_mysql_pass }}'
             priv: '*.*:ALL'
             state: present

   - name: Create WP Database
     mysql_db:
             name: '{{ wp_db_name }}'
             state: present
             login_user: root
             login_password: "{{ mysql_root_pass }}"
             login_unix_socket: /var/run/mysqld/mysqld.sock
     become: yes

   - name: copy WP sample config to config
     template:
             src: config-files/wp-config.php
             dest: /var/www/html/wordpress/wp-config.php
     notify: reload_apache
     become: yes

   - name: change apache default config file
     copy:
             src: config-files/000-default.conf
             dest: /etc/apache2/sites-available/000-default.conf
     notify: reload_apache
   
   handlers:
   - name: reload_apache
     service:
            name: apache2
            state: reloaded             
